#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
	echo "Please run this script with root privileges."
	exit 1
fi

all=""
for arg in "$@"; do
	all=$all$arg" "
done

python3 /usr/share/ihaahi/ACON/acon.py $all
