#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
    echo "Please run this script with root privileges."
    exit 1
fi
directory="/usr/share/ihaahi"
if [ -d "$directory" ]; then
    echo
else
    mkdir /usr/share/ihaahi
fi

mkdir /usr/share/ihaahi/ACON
mv acon.py /usr/share/ihaahi/ACON/


mv acon /usr/local/bin/
chmod +x /usr/local/bin/acon

apt install nftables

echo acon install successfully

